spring:
  application:
    name: ai-code-helper
server:
  port: 8011
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus
        api-key: sk-586ee1fda29d464db2c8fb6560a55f32
      embedding-model:
        model-name: text-embedding-v4
        api-key: sk-586ee1fda29d464db2c8fb6560a55f32
      streaming-chat-model:
        model-name: qwen-plus
        api-key: sk-586ee1fda29d464db2c8fb6560a55f32
bigmodel:
  api-key: a1eeb55cfff34812b2d0f36ddce8d28a.5uPuTbWtq5iyF3xd
ai:
  rag:
    docs:
      path: F:\project\mjh\IDEA\ai-code-helper\src\main\resources\docs
